@echo off
setlocal

:: Poor man's config.h generation for Windows
:: findstr AC_INIT configure.ac
set VR=)
for /F "usebackqtokens=2" %%a in (`findstr AC_INIT configure.ac`) do set TMPAREN=%%a
set FULLVER=%TMPAREN:)=%
:: echo mid %FULLVER%
for /F "usebackqdelims=. tokens=1,2,3" %%b in ('%FULLVER%') do set CVER=%%b,%%c,%%d

echo // Generated by version_h.cmd.
echo #define VERSION "%FULLVER%"
echo #define PACKAGE_VERSION "%FULLVER%"
echo #define PACKAGE_VERSION_COMMAS %CVER%
echo #define PACKAGE_VERSION_NTS "%FULLVER%\0"

echo @set PACKAGE_VERSION=%FULLVER%> setpversion.cmd
echo @exit /b 0 >> setpversion.cmd
