// Generated by Refly
namespace System.Data.Hsqldb.Client.UnitTests
{
    using System;
    using TestCoverage;
    using TestDoubles;
    using NUnit.Framework;
    
    
    [TestFixture()]
    [TestSubjectClassAttribute(TestSubject=typeof(System.Data.Hsqldb.Client.HsqlParameterCollection))]
    public class TestHsqlParameterCollection
    {
        
        [TestSubjectMemberAttribute(MemeberName="Add")]
        [Test()]
        public virtual void Add()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlParameterCollection TestSubject = new System.Data.Hsqldb.Client.HsqlParameterCollection();

            // Create Test Method Parameters
            System.Data.Hsqldb.Client.HsqlParameter value = new System.Data.Hsqldb.Client.HsqlParameter();

            TestSubject.Add(value);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="Add")]
        [Test()]
        public virtual void Add()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlParameterCollection TestSubject = new System.Data.Hsqldb.Client.HsqlParameterCollection();

            // Create Test Method Parameters
            object value = new object();

            TestSubject.Add(value);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="AddRange")]
        [Test()]
        public virtual void AddRange()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlParameterCollection TestSubject = new System.Data.Hsqldb.Client.HsqlParameterCollection();

            // Create Test Method Parameters
            RecorderArray valuesRecording = new RecorderArray();

            TestSubject.AddRange(valuesRecording);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="AddRange")]
        [Test()]
        public virtual void AddRange()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlParameterCollection TestSubject = new System.Data.Hsqldb.Client.HsqlParameterCollection();

            // Create Test Method Parameters
        }
        
        [TestSubjectMemberAttribute(MemeberName="Clear")]
        [Test()]
        public virtual void Clear()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlParameterCollection TestSubject = new System.Data.Hsqldb.Client.HsqlParameterCollection();


            TestSubject.Clear();

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="Clone")]
        [Test()]
        public virtual void Clone()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlParameterCollection TestSubject = new System.Data.Hsqldb.Client.HsqlParameterCollection();


            TestSubject.Clone();

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="Contains")]
        [Test()]
        public virtual void Contains()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlParameterCollection TestSubject = new System.Data.Hsqldb.Client.HsqlParameterCollection();

            // Create Test Method Parameters
            object value = new object();

            TestSubject.Contains(value);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="Contains")]
        [Test()]
        public virtual void Contains()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlParameterCollection TestSubject = new System.Data.Hsqldb.Client.HsqlParameterCollection();

            // Create Test Method Parameters

            // There is no default constuctor for the parameter value type String.
            string value;


            TestSubject.Contains(value);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="CopyTo")]
        [Test()]
        public virtual void CopyTo()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlParameterCollection TestSubject = new System.Data.Hsqldb.Client.HsqlParameterCollection();

            // Create Test Method Parameters
            RecorderArray arrayRecording = new RecorderArray();

            // There is no default constuctor for the parameter index type Int32.
            int index;


            TestSubject.CopyTo(arrayRecording, index);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetEnumerator")]
        [Test()]
        public virtual void GetEnumerator()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlParameterCollection TestSubject = new System.Data.Hsqldb.Client.HsqlParameterCollection();


            TestSubject.GetEnumerator();

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="IndexOf")]
        [Test()]
        public virtual void IndexOf()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlParameterCollection TestSubject = new System.Data.Hsqldb.Client.HsqlParameterCollection();

            // Create Test Method Parameters
            object value = new object();

            TestSubject.IndexOf(value);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="IndexOf")]
        [Test()]
        public virtual void IndexOf()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlParameterCollection TestSubject = new System.Data.Hsqldb.Client.HsqlParameterCollection();

            // Create Test Method Parameters

            // There is no default constuctor for the parameter parameterName type String.
            string parameterName;


            TestSubject.IndexOf(parameterName);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="Insert")]
        [Test()]
        public virtual void Insert()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlParameterCollection TestSubject = new System.Data.Hsqldb.Client.HsqlParameterCollection();

            // Create Test Method Parameters

            // There is no default constuctor for the parameter index type Int32.
            int index;

            object value = new object();

            TestSubject.Insert(index, value);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="Remove")]
        [Test()]
        public virtual void Remove()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlParameterCollection TestSubject = new System.Data.Hsqldb.Client.HsqlParameterCollection();

            // Create Test Method Parameters
            object value = new object();

            TestSubject.Remove(value);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="RemoveAt")]
        [Test()]
        public virtual void RemoveAt()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlParameterCollection TestSubject = new System.Data.Hsqldb.Client.HsqlParameterCollection();

            // Create Test Method Parameters

            // There is no default constuctor for the parameter index type Int32.
            int index;


            TestSubject.RemoveAt(index);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="RemoveAt")]
        [Test()]
        public virtual void RemoveAt()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlParameterCollection TestSubject = new System.Data.Hsqldb.Client.HsqlParameterCollection();

            // Create Test Method Parameters

            // There is no default constuctor for the parameter parameterName type String.
            string parameterName;


            TestSubject.RemoveAt(parameterName);

            // 
            // Write your assertions here.
            // 
        }
    }
}
