// Generated by Refly
namespace System.Data.Hsqldb.Client.UnitTests
{
    using System;
    using TestCoverage;
    using TestDoubles;
    using NUnit.Framework;
    
    
    [TestFixture()]
    [TestSubjectClassAttribute(TestSubject=typeof(System.Data.Hsqldb.Client.HsqlDataReader))]
    public class TestHsqlDataReader
    {
        
        [TestSubjectMemberAttribute(MemeberName="Close")]
        [Test()]
        public virtual void Close()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);


            TestSubject.Close();

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="FromByteArray")]
        [Test()]
        public virtual void FromByteArray()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetBoolean")]
        [Test()]
        public virtual void GetBoolean()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetBoolean(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetByte")]
        [Test()]
        public virtual void GetByte()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetByte(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetBytes")]
        [Test()]
        public virtual void GetBytes()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            // There is no default constuctor for the parameter dataOffset type Int64.
            long dataOffset;

        }
        
        [TestSubjectMemberAttribute(MemeberName="GetChar")]
        [Test()]
        public virtual void GetChar()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetChar(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetChars")]
        [Test()]
        public virtual void GetChars()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            // There is no default constuctor for the parameter dataOffset type Int64.
            long dataOffset;

        }
        
        [TestSubjectMemberAttribute(MemeberName="GetData")]
        [Test()]
        public virtual void GetData()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetData(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetDataTypeName")]
        [Test()]
        public virtual void GetDataTypeName()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetDataTypeName(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetDateTime")]
        [Test()]
        public virtual void GetDateTime()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetDateTime(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetDecimal")]
        [Test()]
        public virtual void GetDecimal()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetDecimal(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetDouble")]
        [Test()]
        public virtual void GetDouble()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetDouble(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetEnumerator")]
        [Test()]
        public virtual void GetEnumerator()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);


            TestSubject.GetEnumerator();

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetFieldType")]
        [Test()]
        public virtual void GetFieldType()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetFieldType(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetFloat")]
        [Test()]
        public virtual void GetFloat()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetFloat(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetGuid")]
        [Test()]
        public virtual void GetGuid()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetGuid(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetInt16")]
        [Test()]
        public virtual void GetInt16()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetInt16(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetInt32")]
        [Test()]
        public virtual void GetInt32()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetInt32(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetInt64")]
        [Test()]
        public virtual void GetInt64()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetInt64(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetName")]
        [Test()]
        public virtual void GetName()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetName(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetOrdinal")]
        [Test()]
        public virtual void GetOrdinal()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter name type String.
            string name;


            TestSubject.GetOrdinal(name);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetProviderSpecificFieldType")]
        [Test()]
        public virtual void GetProviderSpecificFieldType()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetProviderSpecificFieldType(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetProviderSpecificValue")]
        [Test()]
        public virtual void GetProviderSpecificValue()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetProviderSpecificValue(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetProviderSpecificValues")]
        [Test()]
        public virtual void GetProviderSpecificValues()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSchemaTable")]
        [Test()]
        public virtual void GetSchemaTable()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);


            TestSubject.GetSchemaTable();

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlBinary")]
        [Test()]
        public virtual void GetSqlBinary()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetSqlBinary(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlBoolean")]
        [Test()]
        public virtual void GetSqlBoolean()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetSqlBoolean(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlByte")]
        [Test()]
        public virtual void GetSqlByte()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetSqlByte(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlBytes")]
        [Test()]
        public virtual void GetSqlBytes()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetSqlBytes(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlChars")]
        [Test()]
        public virtual void GetSqlChars()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetSqlChars(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlDateTime")]
        [Test()]
        public virtual void GetSqlDateTime()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetSqlDateTime(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlDecimal")]
        [Test()]
        public virtual void GetSqlDecimal()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetSqlDecimal(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlDouble")]
        [Test()]
        public virtual void GetSqlDouble()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetSqlDouble(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlGuid")]
        [Test()]
        public virtual void GetSqlGuid()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetSqlGuid(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlInt16")]
        [Test()]
        public virtual void GetSqlInt16()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetSqlInt16(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlInt32")]
        [Test()]
        public virtual void GetSqlInt32()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetSqlInt32(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlInt64")]
        [Test()]
        public virtual void GetSqlInt64()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetSqlInt64(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlMoney")]
        [Test()]
        public virtual void GetSqlMoney()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetSqlMoney(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlSingle")]
        [Test()]
        public virtual void GetSqlSingle()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetSqlSingle(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlString")]
        [Test()]
        public virtual void GetSqlString()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetSqlString(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlValue")]
        [Test()]
        public virtual void GetSqlValue()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetSqlValue(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlValues")]
        [Test()]
        public virtual void GetSqlValues()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetSqlXml")]
        [Test()]
        public virtual void GetSqlXml()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetSqlXml(ordinal);

            // 
            // Write your assertions here.
            // 
            Assert.AreEqual("<Please replace with valid value.>", TestSubject.Position);
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetString")]
        [Test()]
        public virtual void GetString()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetString(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetValue")]
        [Test()]
        public virtual void GetValue()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.GetValue(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="GetValues")]
        [Test()]
        public virtual void GetValues()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters
        }
        
        [TestSubjectMemberAttribute(MemeberName="IsDBNull")]
        [Test()]
        public virtual void IsDBNull()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter ordinal type Int32.
            int ordinal;


            TestSubject.IsDBNull(ordinal);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="NextResult")]
        [Test()]
        public virtual void NextResult()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);


            TestSubject.NextResult();

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="Read")]
        [Test()]
        public virtual void Read()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);


            TestSubject.Read();

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="ReadFromStream")]
        [Test()]
        public virtual void ReadFromStream()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters
            RecorderStream streamRecording = new RecorderStream();

            TestSubject.ReadFromStream(streamRecording);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="ReadResult")]
        [Test()]
        public virtual void ReadResult()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters
            RecorderStream streamRecording = new RecorderStream();

            TestSubject.ReadResult(streamRecording);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="ToByteArray")]
        [Test()]
        public virtual void ToByteArray()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters

            // There is no default constuctor for the parameter reader type HsqlDataReader.
            System.Data.Hsqldb.Client.HsqlDataReader reader;


            TestSubject.ToByteArray(reader);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="WriteResult")]
        [Test()]
        public virtual void WriteResult()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters
            RecorderStream streamRecording = new RecorderStream();

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            TestSubject.WriteResult(streamRecording, result);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="WriteToStream")]
        [Test()]
        public virtual void WriteToStream()
        {
            // Create Constructor Parameters

            // There is no default constuctor for the parameter result type Result.
            org.hsqldb.Result result;


            System.Data.Hsqldb.Client.HsqlDataReader TestSubject = new System.Data.Hsqldb.Client.HsqlDataReader(result);

            // Create Test Method Parameters
            RecorderStream streamRecording = new RecorderStream();

            // There is no default constuctor for the parameter reader type HsqlDataReader.
            System.Data.Hsqldb.Client.HsqlDataReader reader;


            TestSubject.WriteToStream(streamRecording, reader);

            // 
            // Write your assertions here.
            // 
        }
    }
}
