// Generated by Refly
namespace System.Data.Hsqldb.Client.UnitTests
{
    using System;
    using TestCoverage;
    using TestDoubles;
    using NUnit.Framework;
    
    
    [TestFixture()]
    [TestSubjectClassAttribute(TestSubject=typeof(System.Data.Hsqldb.Client.HsqlDataSourceEnumerator))]
    public class TestHsqlDataSourceEnumerator
    {
        
        [TestSubjectMemberAttribute(MemeberName="GetDataSources")]
        [Test()]
        public virtual void GetDataSources()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlDataSourceEnumerator TestSubject = new System.Data.Hsqldb.Client.HsqlDataSourceEnumerator();


            TestSubject.GetDataSources();

            // 
            // Write your assertions here.
            // 
        }
    }
}
