// Generated by Refly
namespace System.Data.Hsqldb.Client.UnitTests
{
    using System;
    using TestCoverage;
    using TestDoubles;
    using NUnit.Framework;
    
    
    [TestFixture()]
    [TestSubjectClassAttribute(TestSubject=typeof(System.Data.Hsqldb.Client.HsqlDataAdapter))]
    public class TestHsqlDataAdapter
    {
        
        [TestSubjectMemberAttribute(MemeberName="Clone")]
        [Test()]
        public virtual void Clone()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlDataAdapter TestSubject = new System.Data.Hsqldb.Client.HsqlDataAdapter();


            TestSubject.Clone();

            // 
            // Write your assertions here.
            // 
        }
    }
}
