// Generated by Refly
namespace System.Data.Hsqldb.Client.UnitTests
{
    using System;
    using TestCoverage;
    using TestDoubles;
    using NUnit.Framework;
    
    
    [TestFixture()]
    [TestSubjectClassAttribute(TestSubject=typeof(System.Data.Hsqldb.Client.HsqlRowUpdatedEventHandler))]
    public class TestHsqlRowUpdatedEventHandler
    {
        
        [TestSubjectMemberAttribute(MemeberName="BeginInvoke")]
        [Test()]
        public virtual void BeginInvoke()
        {
        }
        
        [TestSubjectMemberAttribute(MemeberName="EndInvoke")]
        [Test()]
        public virtual void EndInvoke()
        {
        }
        
        [TestSubjectMemberAttribute(MemeberName="Invoke")]
        [Test()]
        public virtual void Invoke()
        {
        }
    }
}
