// Generated by Refly
namespace System.Data.Hsqldb.Client.UnitTests
{
    using System;
    using TestCoverage;
    using TestDoubles;
    using NUnit.Framework;
    
    
    [TestFixture()]
    [TestSubjectClassAttribute(TestSubject=typeof(System.Data.Hsqldb.Client.HsqlDataPermission))]
    public class TestHsqlDataPermission
    {
        
        [TestSubjectMemberAttribute(MemeberName="Add")]
        [Test()]
        public virtual void Add()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlDataPermission TestSubject = new System.Data.Hsqldb.Client.HsqlDataPermission();

            // Create Test Method Parameters

            // There is no default constuctor for the parameter connectionString type String.
            string connectionString;


            // There is no default constuctor for the parameter restrictions type String.
            string restrictions;


            // There is no default constuctor for the parameter behavior type KeyRestrictionBehavior.
            System.Data.KeyRestrictionBehavior behavior;


            TestSubject.Add(connectionString, restrictions, behavior);

            // 
            // Write your assertions here.
            // 
        }
        
        [TestSubjectMemberAttribute(MemeberName="Copy")]
        [Test()]
        public virtual void Copy()
        {
            // Create Constructor Parameters

            System.Data.Hsqldb.Client.HsqlDataPermission TestSubject = new System.Data.Hsqldb.Client.HsqlDataPermission();


            TestSubject.Copy();

            // 
            // Write your assertions here.
            // 
        }
    }
}
